### ISSUE TITLE
No such file or directory: 'query_label.xml'

### ISSUE THREAD

**Issue by Zhanghao5200** [michuanhaohao/AICITY2021_Track2_DMT#4]
I found that your train_track.txt file is different from the original data file, and you have generated a new query_label.xml file, which also does not exist in the original data. Can you provide these documents?

**Comment by michuanhaohao** [comment]
I did not generated a new query_label.xml. The query_label.xml is provided by the dataset. I modified the first line to 'encoding="utf-8"'. Because there was a problem with text decoding. Many teams known it. In addition, I did not use tracklet ID during the training stage, therefore I did not change train_track.txt. The model loads tracklet ID but does not use it. You can random give a tracklet ID for the training image. The results can be reproduced.

**Comment by michuanhaohao** [comment]
![image](https://user-images.githubusercontent.com/23547900/122898102-334d2a80-d37d-11eb-8972-b8d99972b821.png)
All these files are provided by the dataset.

**Comment by Zhanghao5200** [comment]
Thanks,I find the problem.It's all my fault,my dataset is cityFlow2020,not 2021.So there are some differents between two datasets.

**Comment by michuanhaohao** [comment]
ok
